---

- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    parallel_builds: 4
    boxes:
      - box_name: centos8-stream
        box_vars: virtualbox.pkrvars.hcl
        only: virtualbox-iso.packer-centos-virtualbox
      # deprecated:
      # - box_name: centos8
      #   box_vars: virtualbox.pkrvars.hcl
      #   only: virtualbox-iso.packer-centos-virtualbox
      # - box_name: centos7
      #   box_vars: virtualbox.pkrvars.hcl
      #   only: virtualbox-iso.packer-centos-virtualbox

  tasks:

    - include_tasks: build-batch.yml
      loop: "{{ boxes | batch(parallel_builds) | list}}"
      loop_control:
        loop_var: "batch_item"
