---

# tasks for installing required/useful packages

- block:
    - name: import epel gpg key
      rpm_key:
        key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
        state: present

    - name: install epel repo
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present

  when:
    - ansible_os_family == "RedHat"
    - ansible_virtualization_type | lower == "virtualbox" or install_epel | default(false)

- name: upgrade all packages
  package:
    name: "*"
    state: latest

- name: install useful packages
  package:
    name:
      - vim
      - tmux
      - curl
      - wget
      - git
      - rsync
      - tcpdump
      - net-tools
      - bind-utils
      - nfs-utils
    state: latest
